### ISSUE TITLE
[Feature request] Time param (-t) unit in ms instead of sec

### ISSUE THREAD

**Issue by petsam** [manjaro/pacman-mirrors#117]
If it is possible please change the response time limit to milliseconds instead of seconds.
The `second` limit seems too wide for the purpose it serves IMHO.
It is supposed to be multiplied by a large amount of downloading data, combined with speed.
I cannot explain it well with my English language skills.
Time is good to sort on but when it comes as a limit, it would be fair to be in milliseconds if it makes sense for the server capabilities (don't know enough of that).

**Comment by fhdk** [comment]
You can change the timeout with -t  but the timeout only comes into play if the probed mirror's response time is longer than the default 2 seconds .

Also - when probing ssl enabled mirrors - handshake also takes time which is why pacman-mirrors doubles the timeout value when probing mirrors using https.

Again this is a feature - not a bug.
