### ISSUE TITLE
ranking testing repository only save unreachable mirrors in the mirrorlist

### ISSUE THREAD

**Issue by scachemaille** [manjaro/pacman-mirrors#67]
when we run 
sudo pacman-mirrors -g -m rank -b testing
pacman-mirros only save unreachable mirrors in the mirrorlist file.

see [the forum post](https://forum.manjaro.org/t/cannot-switch-to-testing/19684/8)
unstable branche with pacman-mirrorlist V20170212-1

no problems with new version (-dev package)

**Comment by fhdk** [comment]
@scachemaille 
I hope you don't mind me not putting much effort in this one as I have no clue at all.

The ranking does no differentiating on branch so it is weird that you have -b stable and -b unstable working correct. If the problem was consistent to all branches then we have an issue.

Also a further rewrite have been made for v 4.0.0 so if we call it a mystery and go on with our lives.

What do think?

**Comment by scachemaille** [comment]
I don't know. when I tried to replicate it on -dev I did not know it was downloading the mirrors list every times. and I think there was no unreachable mirrors. when I will be home I may try again. if the problem does not arrive with -dev and that it should replace the default package I don't mind yes. ;)

**Comment by scachemaille** [comment]
resinstalled the package and can't replicate the problem anymore. weird weird weird. ;)

**Comment by fhdk** [comment]
https://github.com/manjaro/pacman-mirrors/issues/71
